export const scheduleDay: any[] = [
  {
    day: 'Monday',
    hours: [
      { h: 0, appointments: [] },
      { h: 1, appointments: [] },
      { h: 2, appointments: [] },
      { h: 3, appointments: [] },
      { h: 4, appointments: [] },
      { h: 5, appointments: [] },
      { h: 6, appointments: [] },
      { h: 7, appointments: [] },
      { h: 8, appointments: [] },
      { h: 9, appointments: [] },
      { h: 10, appointments: [] },
      { h: 11, appointments: [] },
    ],
  },
  {
    day: 'Thusday',
    hours: [
      { h: 0, appointments: [] },
      { h: 1, appointments: [] },
      { h: 2, appointments: [] },
      { h: 3, appointments: [] },
      { h: 4, appointments: [] },
      { h: 5, appointments: [] },
      { h: 6, appointments: [] },
      { h: 7, appointments: [] },
      { h: 8, appointments: [] },
      { h: 9, appointments: [] },
      { h: 10, appointments: [] },
      { h: 11, appointments: [] },
    ],
  },
  {
    day: 'Thursday',
    hours: [
      { h: 0, appointments: [] },
      { h: 1, appointments: [] },
      { h: 2, appointments: [] },
      { h: 3, appointments: [] },
      { h: 4, appointments: [] },
      { h: 5, appointments: [] },
      { h: 6, appointments: [] },
      { h: 7, appointments: [] },
      { h: 8, appointments: [] },
      { h: 9, appointments: [] },
      { h: 10, appointments: [] },
      { h: 11, appointments: [] },
    ],
  },
  {
    day: 'Wensday',
    hours: [
      { h: 0, appointments: [] },
      { h: 1, appointments: [] },
      { h: 2, appointments: [] },
      { h: 3, appointments: [] },
      { h: 4, appointments: [] },
      { h: 5, appointments: [] },
      { h: 6, appointments: [] },
      { h: 7, appointments: [] },
      { h: 8, appointments: [] },
      { h: 9, appointments: [] },
      { h: 10, appointments: [] },
      { h: 11, appointments: [] },
    ],
  },
  {
    day: 'Friday',
    hours: [
      { h: 0, appointments: [] },
      { h: 1, appointments: [] },
      { h: 2, appointments: [] },
      { h: 3, appointments: [] },
      { h: 4, appointments: [] },
      { h: 5, appointments: [] },
      { h: 6, appointments: [] },
      { h: 7, appointments: [] },
      { h: 8, appointments: [] },
      { h: 9, appointments: [] },
      { h: 10, appointments: [] },
      { h: 11, appointments: [] },
    ],
  },
];
export const days: string[] = ['Luni', 'Marti', 'Miercuri', 'Joi', 'Vineri'];
export const hours: string[] = [
  '8-9',
  '9-10',
  '10-11',
  '11-12',
  '12-13',
  '13-14',
  '14-15',
  '15-16',
  '16-17',
  '17-18',
  '18-19',
  '19-20',
];
